// Writes src/test/java/io/github/tandemrng/Derived.java from tandem-cuda's core.hpp, the shared
// device core, so that every port that follows it returns the same values.
//
//   c++ -std=c++17 -I ../tandem-cuda/include tools/gen_derived.cpp -o gen_derived
//   ./gen_derived > src/test/java/io/github/tandemrng/Derived.java
//
// Each case starts from Rng(42) after one bit draw, which leaves the position unaligned.
#include <cinttypes>
#include <cstdio>

#include "tandem/core.hpp"

static const uint32_t RANGES32[] = {1u, 2u, 6u, 1000u, 0xc0000001u, 0xffffffffu};
static const uint64_t RANGES64[] = {1ull, 3ull, 1000000000000ull, 0xc000000000000001ull,
                                    0xffffffffffffffffull};
constexpr int COUNT = 64;

int main() {
    std::printf("// Generated by tools/gen_derived.cpp from tandem-cuda core.hpp. Do not edit.\n");
    std::printf("package io.github.tandemrng;\n\nfinal class Derived {\n    private Derived() {}\n\n");

    std::printf("    static final int[] RANGE32 = {");
    for (uint32_t n : RANGES32)
        std::printf("0x%08" PRIx32 "%s", n, n == RANGES32[5] ? "" : ", ");
    std::printf("};\n    static final int[][] BELOW32 = {\n");
    for (uint32_t n : RANGES32) {
        tandem::Rng g(42);
        g.bit();
        std::printf("        {");
        for (int i = 0; i < COUNT; i++)
            std::printf("%s0x%08" PRIx32, i ? ", " : "", g.urand(n));
        std::printf("},\n");
    }
    std::printf("    };\n    static final long[] BELOW32_END = {");
    for (uint32_t n : RANGES32) {
        tandem::Rng g(42);
        g.bit();
        for (int i = 0; i < COUNT; i++)
            g.urand(n);
        std::printf("%" PRIu64 "L%s", g.position(), n == RANGES32[5] ? "" : ", ");
    }

    std::printf("};\n\n    static final long[] RANGE64 = {");
    for (uint64_t n : RANGES64)
        std::printf("0x%016" PRIx64 "L%s", n, n == RANGES64[4] ? "" : ", ");
    std::printf("};\n    static final long[][] BELOW64 = {\n");
    for (uint64_t n : RANGES64) {
        tandem::Rng g(42);
        g.bit();
        std::printf("        {");
        for (int i = 0; i < COUNT; i++)
            std::printf("%s0x%016" PRIx64 "L", i ? ", " : "", g.urand64(n));
        std::printf("},\n");
    }
    std::printf("    };\n    static final long[] BELOW64_END = {");
    for (uint64_t n : RANGES64) {
        tandem::Rng g(42);
        g.bit();
        for (int i = 0; i < COUNT; i++)
            g.urand64(n);
        std::printf("%" PRIu64 "L%s", g.position(), n == RANGES64[4] ? "" : ", ");
    }

    // log and cos differ in the last place between libms. Twelve digits keep the file identical
    // on every platform, and the tests compare within a relative 1e-12.
    tandem::Rng g(42);
    g.bit();
    std::printf("};\n\n    static final double[] NORMAL = {\n");
    for (int i = 0; i < COUNT; i++)
        std::printf("        %.12g,\n", g.normal());
    std::printf("    };\n    static final long NORMAL_END = %" PRIu64 "L;\n}\n", g.position());
    return 0;
}
