#!/usr/bin/env python3
"""Turn the spec's ziggurat tables into ZigTables.java, value for value, as hexadecimal literals.

Usage: tools/gen_zig_tables.py path/to/normal_f64_zig1024.json > src/main/java/io/github/tandemrng/ZigTables.java
"""
import hashlib
import json
import sys

SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"


def rows(items, per_line):
    return ",\n".join("        " + ", ".join(items[i:i + per_line]) for i in range(0, len(items), per_line))


def hexf(s):
    x = float.fromhex(s)
    assert float.fromhex(x.hex()) == x
    return x.hex()


def main(path):
    raw = open(path, "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SHA256:
        sys.exit(f"{path}: SHA-256 {digest}, expected {SHA256}")
    t = json.loads(raw)
    n = t["layers"]
    assert n == 1024 and len(t["W"]) == n and len(t["K"]) == n and len(t["Y"]) == n + 1
    assert all(0 <= k < 2**53 for k in t["K"]) and t["K"][-1] == 0
    print(f"""// Generated by tools/gen_zig_tables.py from tandem-spec tables/normal_f64_zig1024.json,
// SHA-256 {SHA256}. Do not edit.
package io.github.tandemrng;

/** The 1024-layer ziggurat of the double normals, spec Appendix A: widths, thresholds, heights. */
final class ZigTables {{
    private ZigTables() {{}}

    static final double R = {hexf(t["R"])};

    static final double[] W = {{
{rows([hexf(w) for w in t["W"]], 4)}
    }};

    static final long[] K = {{
{rows([f"{k}L" for k in t["K"]], 5)}
    }};

    static final double[] Y = {{
{rows([hexf(y) for y in t["Y"]], 4)}
    }};
}}""")


if __name__ == "__main__":
    main(sys.argv[1])
