// Writes src/test/java/io/github/tandemrng/Derived.java from tandem-cuda's core.hpp, the shared
// device core, so that every port that follows it returns the same values.
//
//   c++ -std=c++17 -I ../tandem-cuda/include tools/gen_derived.cpp -o gen_derived
//   ./gen_derived > src/test/java/io/github/tandemrng/Derived.java
//
// Each case starts from Rng(42) after one bit draw, which leaves the position unaligned.
#include <cinttypes>
#include <cmath>
#include <cstdio>
#include <initializer_list>

#include "tandem/core.hpp"

static const uint32_t RANGES32[] = {1u, 2u, 6u, 1000u, 0xc0000001u, 0xffffffffu};
static const uint64_t RANGES64[] = {1ull, 3ull, 1000000000000ull, 0xc000000000000001ull,
                                    0xffffffffffffffffull};
constexpr int COUNT = 64;
static const uint32_t FILL32[] = {3u, 7u, 10u, 1000u, 0x80000001u, 0xffffffffu};
static const uint64_t FILL64[] = {3ull, 7ull, 10ull, 1000ull, 0x80000001ull, 0xffffffffull,
                                  0x8000000000000001ull, 0xffffffffffffffffull};

// The bounded-fill contract spelled out with Rng calls, as tandem-cuda's tests do.
static uint32_t below32(const tandem::Rng &root, uint32_t range, uint64_t e) {
    uint64_t m = (uint64_t)root.at_urand(e) * range;
    if ((uint32_t)m < range) {
        uint32_t t = (0u - range) % range;
        if ((uint32_t)m < t) {
            tandem::Rng f = root.sub(tandem::PURPOSE_BELOW32).split(e);
            do m = (uint64_t)f.urand() * range; while ((uint32_t)m < t);
        }
    }
    return (uint32_t)(m >> 32);
}

static uint64_t below64(const tandem::Rng &root, uint64_t range, uint64_t e) {
    uint64_t x = root.at_urand64(e), lo = x * range;
    if (lo < range) {
        uint64_t t = (0u - range) % range;
        if (lo < t) {
            tandem::Rng f = root.sub(tandem::PURPOSE_BELOW64).split(e);
            do {
                x = f.urand64();
                lo = x * range;
            } while (lo < t);
        }
    }
    return tandem::mulhi64(x, range);
}

// The double Box-Muller pair of two uniforms, which the float fixtures round to float: the float
// core can differ by an ulp between compilers, this rounding is stable. It is the polynomial step
// tandem-cuda had before the ziggurat, with explicit fused multiply-adds, so every platform
// writes the same file.
static tandem::Pair2<double> box_muller(double a, double b) {
    double r = std::sqrt(tandem::detail::neg2_log_f64(1.0 - a));
    int64_t q = (int64_t)(b * 4.0 + 0.5);
    double f = std::fma(-(double)q, 0.25, b), th = f * 6.283185307179586, w = th * th;
    double hs = std::fma(w, std::fma(w, std::fma(w, std::fma(w, std::fma(w, 1.5914650986900946e-10,
                -2.5051097984389413e-08), 2.755731600073921e-06), -0.00019841269836630226),
                0.008333333333330813), -0.16666666666666669);
    double hc = std::fma(w, std::fma(w, std::fma(w, std::fma(w, std::fma(w, 2.0665708703855164e-09,
                -2.7555858522576447e-07), 2.480158263811954e-05), -0.0013888888882156126),
                0.04166666666663108), -0.4999999999999997);
    double sn = th * std::fma(w, hs, 1.0), cs = std::fma(w, hc, 1.0);
    double x = q & 1 ? sn : cs, y = q & 1 ? cs : sn;
    if ((q + 1) & 2) x = -x;
    if (q & 2) y = -y;
    return {r * x, r * y};
}

int main() {
    std::printf("// Generated by tools/gen_derived.cpp from tandem-cuda core.hpp. Do not edit.\n");
    std::printf("package io.github.tandemrng;\n\nfinal class Derived {\n    private Derived() {}\n\n");

    std::printf("    static final int[] RANGE32 = {");
    for (uint32_t n : RANGES32)
        std::printf("0x%08" PRIx32 "%s", n, n == RANGES32[5] ? "" : ", ");
    std::printf("};\n    static final int[][] BELOW32 = {\n");
    for (uint32_t n : RANGES32) {
        tandem::Rng g(42);
        g.bit();
        std::printf("        {");
        for (int i = 0; i < COUNT; i++)
            std::printf("%s0x%08" PRIx32, i ? ", " : "", g.urand(n));
        std::printf("},\n");
    }
    std::printf("    };\n    static final long[] BELOW32_END = {");
    for (uint32_t n : RANGES32) {
        tandem::Rng g(42);
        g.bit();
        for (int i = 0; i < COUNT; i++)
            g.urand(n);
        std::printf("%" PRIu64 "L%s", g.position(), n == RANGES32[5] ? "" : ", ");
    }

    std::printf("};\n\n    static final long[] RANGE64 = {");
    for (uint64_t n : RANGES64)
        std::printf("0x%016" PRIx64 "L%s", n, n == RANGES64[4] ? "" : ", ");
    std::printf("};\n    static final long[][] BELOW64 = {\n");
    for (uint64_t n : RANGES64) {
        tandem::Rng g(42);
        g.bit();
        std::printf("        {");
        for (int i = 0; i < COUNT; i++)
            std::printf("%s0x%016" PRIx64 "L", i ? ", " : "", g.urand64(n));
        std::printf("},\n");
    }
    std::printf("    };\n    static final long[] BELOW64_END = {");
    for (uint64_t n : RANGES64) {
        tandem::Rng g(42);
        g.bit();
        for (int i = 0; i < COUNT; i++)
            g.urand64(n);
        std::printf("%" PRIu64 "L%s", g.position(), n == RANGES64[4] ? "" : ", ");
    }

    // Double normals: the ziggurat, exact on every platform, so 17 digits pin the bits. 2 COUNT
    // scalar draws, about one miss.
    tandem::Rng g(42);
    g.bit();
    std::printf("};\n\n    static final double[] NORMAL = {\n");
    for (int i = 0; i < 2 * COUNT; i++)
        std::printf("        %.17g,\n", g.normal());
    std::printf("    };\n    static final long NORMAL_END = %" PRIu64 "L;\n", g.position());

    // Float normals agree across ports to a few ulps. Element 2i of the array is the cos half of
    // pair i and 2i + 1 the sin half.
    tandem::Rng f(42);
    f.bit();
    std::printf("\n    static final float[] NORMALF = {\n");
    for (int i = 0; i < COUNT; i++) {
        float a = f.frand();
        auto z = box_muller((double)a, (double)f.frand());
        std::printf("        %.7gf,\n        %.7gf,\n", (double)(float)z.z0, (double)(float)z.z1);
    }
    std::printf("    };\n    static final long NORMALF_END = %" PRIu64 "L;\n", f.position());

    // Normal fills of 33 elements from the key of seed 42, K = 32. Double: element e is the
    // ziggurat of UInt64 draw e, the sequence of normal() calls. Float: pair j is one step of
    // uniforms 2j and 2j + 1 of the plain fill.
    tandem::Rng nroot(42, 0, 32);
    std::printf("\n    static final long[] FILLN_POS64 = {0L, 64L, 1000L};\n");
    std::printf("    static final double[][] FILLN64 = {\n");
    for (uint64_t pos : {0ull, 64ull, 1000ull}) {
        tandem::Rng r = nroot;
        r.set_position(pos);
        std::printf("        {");
        for (int e = 0; e < 33; e++)
            std::printf("%s%.17g", e ? ", " : "", r.normal());
        std::printf("},\n");
    }
    std::printf("    };\n    static final long[] FILLN_POS32 = {0L, 32L, 64L, 96L, 1000L};\n");
    std::printf("    static final float[][] FILLN32 = {\n");
    for (uint64_t pos : {0ull, 32ull, 64ull, 96ull, 1000ull}) {
        tandem::Rng r = nroot;
        r.set_position(pos);
        std::printf("        {");
        for (int j = 0; j < 17; j++) {
            auto z = box_muller((double)r.at_frand(2 * j), (double)r.at_frand(2 * j + 1));
            std::printf("%s%.7gf", j ? ", " : "", (double)(float)z.z0);
            if (2 * j + 1 < 33) std::printf(", %.7gf", (double)(float)z.z1);
        }
        std::printf("},\n");
    }
    std::printf("    };\n");

    // Bounded fills: element e takes draw e of the plain fill, and a rejected draw retries on
    // split(e) of sub(PURPOSE_BELOW) from position 0. Key of seed 42, K = 32, position 0.
    tandem::Rng root(42, 0, 32);
    std::printf("\n    static final int[] FILL_RANGE32 = {");
    for (uint32_t r : FILL32)
        std::printf("0x%08" PRIx32 "%s", r, r == FILL32[5] ? "" : ", ");
    std::printf("};\n    static final int[][] FILL_BELOW32 = {\n");
    for (uint32_t r : FILL32) {
        std::printf("        {");
        for (int e = 0; e < COUNT; e++)
            std::printf("%s0x%08" PRIx32, e ? ", " : "", below32(root, r, e));
        std::printf("},\n");
    }
    std::printf("    };\n\n    static final long[] FILL_RANGE64 = {");
    for (uint64_t r : FILL64)
        std::printf("0x%016" PRIx64 "L%s", r, r == FILL64[7] ? "" : ", ");
    std::printf("};\n    static final long[][] FILL_BELOW64 = {\n");
    for (uint64_t r : FILL64) {
        std::printf("        {");
        for (int e = 0; e < COUNT; e++)
            std::printf("%s0x%016" PRIx64 "L", e ? ", " : "", below64(root, r, e));
        std::printf("},\n");
    }

    // Bounded fills from unaligned starts, as in tandem-c's cross_fill_below.h: the fallback of
    // draw i is keyed by the global draw index, aligned start over the width plus i.
    const uint64_t STARTS[] = {1ull, 12345ull};
    std::printf("    };\n\n    static final long[] FILLS_START = {1L, 12345L};\n    static final int[][][] FILLS_BELOW32 = {\n");
    for (uint64_t start : STARTS) {
        std::printf("        {\n");
        for (uint32_t n : FILL32) {
            tandem::Rng g(42);
            g.set_position(start);
            tandem::Key k = g.key();
            uint64_t first = (start + 31) / 32;
            std::printf("            {");
            for (int i = 0; i < COUNT; i++)
                std::printf("%s0x%08" PRIx32, i ? ", " : "",
                            tandem::below_u32(g.urand(), n, k.w, g.chunk_length(), first + (uint64_t)i));
            std::printf("},\n");
        }
        std::printf("        },\n");
    }
    std::printf("    };\n    static final long[][][] FILLS_BELOW64 = {\n");
    for (uint64_t start : STARTS) {
        std::printf("        {\n");
        for (uint64_t n : FILL64) {
            tandem::Rng g(42);
            g.set_position(start);
            tandem::Key k = g.key();
            uint64_t first = (start + 63) / 64;
            std::printf("            {");
            for (int i = 0; i < COUNT; i++)
                std::printf("%s0x%016" PRIx64 "L", i ? ", " : "",
                            tandem::below_u64(g.urand64(), n, k.w, g.chunk_length(), first + (uint64_t)i));
            std::printf("},\n");
        }
        std::printf("        },\n");
    }
    std::printf("    };\n");

    // Exponentials as in tandem-c's cross_exponential.h, which these values equal bit for bit:
    // 64 draws from Rng(42) at aligned and unaligned starts.
    const uint64_t EXP_STARTS[] = {0ull, 1ull, 77ull, 12345ull, 1ull << 30};
    std::printf("\n    static final long[] EXP_START = {0L, 1L, 77L, 12345L, %" PRIu64 "L};\n", 1ull << 30);
    std::printf("    static final double[][] EXP = {\n");
    for (uint64_t start : EXP_STARTS) {
        tandem::Rng g(42);
        g.set_position(start);
        std::printf("        {");
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%.17g", i ? ", " : "", g.exponential());
        std::printf("},\n");
    }
    std::printf("    };\n    static final float[][] EXPF = {\n");
    for (uint64_t start : EXP_STARTS) {
        tandem::Rng g(42);
        g.set_position(start);
        std::printf("        {");
        for (int i = 0; i < COUNT; i++)
            std::printf("%s%.9gf", i ? ", " : "", (double)g.exponentialf());
        std::printf("},\n");
    }
    std::printf("    };\n    static final long[] EXP_END = {");
    for (uint64_t start : EXP_STARTS) {
        tandem::Rng g(42);
        g.set_position(start);
        for (int i = 0; i < COUNT; i++) g.exponential();
        std::printf("%" PRIu64 "L%s", g.position(), start == EXP_STARTS[4] ? "" : ", ");
    }
    std::printf("};\n    static final long[] EXPF_END = {");
    for (uint64_t start : EXP_STARTS) {
        tandem::Rng g(42);
        g.set_position(start);
        for (int i = 0; i < COUNT; i++) g.exponentialf();
        std::printf("%" PRIu64 "L%s", g.position(), start == EXP_STARTS[4] ? "" : ", ");
    }
    std::printf("};\n");
    std::printf("}\n");
    return 0;
}
