#!/usr/bin/env python3
"""Turn the spec's vectors.json into src/test/java/io/github/tandemrng/Vectors.java, so the tests
need no JSON parser.

Usage: tools/gen_vectors.py path/to/vectors.json > src/test/java/io/github/tandemrng/Vectors.java
CI compares the output byte for byte.
"""
import json
import sys


def words(ws):
    return "{" + ", ".join(f"0x{w}" for w in ws) + "}"


def lines(rows):
    return "{\n" + "".join(f"        {r},\n" for r in rows) + "    }"


def main(path):
    v = json.load(open(path))
    out = ["// Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit.",
           "package io.github.tandemrng;",
           "",
           "final class Vectors {",
           "    private Vectors() {}",
           "",
           f"    static final int K = {v['K']};",
           f"    static final int[] KEY = {words(v['key'])};",
           ""]

    out.append("    /** Each row is o, h, o_out, h_out. */")
    out.append("    static final int[][][] T = " + lines(
        "{" + ", ".join(words(t[k]) for k in ("o", "h", "o_out", "h_out")) + "}" for t in v["T"]) + ";")

    for f in v["F"]:
        assert f["domain"] == "DOMAIN_STREAM" and f["aux"] == "AUX_STREAM"
    out.append("    static final long[] F_COUNTER = {" + ", ".join(f"{f['counter']}L" for f in v["F"]) + "};")
    out.append("    static final int[][] F_O = " + lines(words(f["o"]) for f in v["F"]) + ";")
    out.append("    static final int[][] F_H = " + lines(words(f["h"]) for f in v["F"]) + ";")

    out.append("    static final long[] STREAM_FIRST_WORD = {"
               + ", ".join(f"{s['first_word']}L" for s in v["stream_words"]) + "};")
    out.append("    static final int[][] STREAM_WORDS = " + lines(words(s["words"]) for s in v["stream_words"]) + ";")

    d = v["draws_from_position_0"]
    out.append("    static final long[] F64_INDEX = {" + ", ".join(f"{k}L" for k in d["Float64"]) + "};")
    out.append("    static final double[] F64_VALUE = {" + ", ".join(repr(x) for x in d["Float64"].values()) + "};")
    out.append("    static final long[] F32_INDEX = {" + ", ".join(f"{k}L" for k in d["Float32"]) + "};")
    out.append("    static final float[] F32_VALUE = {" + ", ".join(f"{x!r}f" for x in d["Float32"].values()) + "};")
    out.append("    static final long[] BOOL_INDEX = {" + ", ".join(f"{k}L" for k in d["Bool"]) + "};")
    out.append("    static final boolean[] BOOL_VALUE = {"
               + ", ".join(str(bool(x)).lower() for x in d["Bool"].values()) + "};")

    k = v["derived_keys"]
    out.append(f"    static final int[] SPLIT0 = {words(k['split_child_0'])};")
    out.append(f"    static final int[] SPLIT1 = {words(k['split_child_1'])};")
    out.append(f"    static final int[] FORK0 = {words(k['fork_child_0_at_block_0'])};")
    out.append(f"    static final int[] PURPOSE7 = {words(k['purpose_7'])};")

    s = v["seed_whitening"]
    assert 0 <= s["seed"] < 2**128
    out.append(f"    static final long SEED_LO = 0x{s['seed'] & (2**64 - 1):x}L;")
    out.append(f"    static final long SEED_HI = 0x{s['seed'] >> 64:x}L;")
    out.append(f"    static final int[] SEED_KEY = {words(s['key'])};")
    out.append("    static final long[] SEED_F64_INDEX = {" + ", ".join(f"{k}L" for k in s["Float64"]) + "};")
    out.append("    static final double[] SEED_F64_VALUE = {" + ", ".join(repr(x) for x in s["Float64"].values()) + "};")
    out.append("    static final long[] SEED_U32_INDEX = {" + ", ".join(f"{k}L" for k in s["UInt32"]) + "};")
    out.append("    static final int[] SEED_U32_VALUE = {" + ", ".join(f"0x{x}" for x in s["UInt32"].values()) + "};")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
