// Generated by tools/gen_vectors.py from the spec's vectors.json. Do not edit.
package io.github.tandemrng;

final class Vectors {
    private Vectors() {}

    static final int K = 32;
    static final int[] KEY = {0x00000001, 0x00000002, 0x00000003, 0x00000004};

    /** Each row is o, h, o_out, h_out. */
    static final int[][][] T = {
        {{0x00000001, 0x00000002, 0x00000003, 0x00000004}, {0x00000005, 0x00000006, 0x00000007, 0x00000008}, {0x00000017, 0x00150007, 0x00000001, 0x00050008}, {0x9e377ca9, 0x0000e006, 0x02000007, 0x00001820}},
        {{0x00000000, 0x00000000, 0x00000000, 0x00000000}, {0x00000000, 0x00000000, 0x00000000, 0x00000000}, {0x00000000, 0x00000000, 0x00000000, 0x00000000}, {0x9e3779b9, 0x00000000, 0x00000000, 0x00000000}},
    };
    static final long[] F_COUNTER = {0L, 1L};
    static final int[][] F_O = {
        {0x472bef12, 0xc0977c66, 0xd330ac3a, 0xb11a020d},
        {0xb777c10c, 0x2f6b5a5d, 0x67a9ce03, 0x7de06a50},
    };
    static final int[][] F_H = {
        {0xbfa0b6ba, 0xecdbc48e, 0xf1989116, 0xc2374d96},
        {0xd0c2dc4f, 0xe1e50e0f, 0x89efc72c, 0x6e82b062},
    };
    static final long[] STREAM_FIRST_WORD = {0L, 4L, 32L};
    static final int[][] STREAM_WORDS = {
        {0x0a5bcb90, 0x6dfe98bc, 0x9612198a, 0xac115fd8},
        {0x33f598d7, 0xb5c280ca, 0x7a8e7b99, 0x8c362290},
        {0x9da7bac0, 0x4aca79eb, 0xbeb1f65a, 0xe2f0d5a1},
    };
    static final long[] F64_INDEX = {0L, 16L};
    static final double[] F64_VALUE = {0.4296660861094629, 0.2921520424112306};
    static final long[] F32_INDEX = {2L};
    static final float[] F32_VALUE = {0.58621365f};
    static final long[] BOOL_INDEX = {0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 128L};
    static final boolean[] BOOL_VALUE = {false, false, false, false, true, false, false, true, true};
    static final int[] SPLIT0 = {0xe256e9a1, 0x5020f806, 0x3bd3f7dc, 0x5328763d};
    static final int[] SPLIT1 = {0xa9ea3f0b, 0x47f97af0, 0xd1844c53, 0x97e9cee2};
    static final int[] FORK0 = {0x67fd37c5, 0x9dc0b8c6, 0x4e3bd55e, 0xaf3f2216};
    static final int[] PURPOSE7 = {0x8048398f, 0x1678e814, 0xd8823983, 0xc4b1045c};
    static final long SEED_LO = 0x2aL;
    static final long SEED_HI = 0x0L;
    static final int[] SEED_KEY = {0x421d21eb, 0x32d31777, 0x62e7564b, 0xdf2bdf82};
    static final long[] SEED_F64_INDEX = {0L, 2L, 16L};
    static final double[] SEED_F64_VALUE = {0.9829130398628935, 0.47759300283385586, 0.9692135305890753};
    static final long[] SEED_U32_INDEX = {0L};
    static final int[] SEED_U32_VALUE = {0x05e80cec};
}
